# Generated by Django 4.0.6 on 2022-07-20 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('traveled_d', models.FloatField()),
                ('avg_speed', models.FloatField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('speed', models.FloatField()),
                ('lon_acc', models.FloatField()),
                ('lat_acc', models.FloatField()),
                ('time', models.FloatField()),
            ],
        ),
    ]
