# Generated by Django 4.0.6 on 2022-07-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='trafficinfo',
            name='track_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
