# Generated by Django 4.0.6 on 2022-07-21 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0004_rename_county_location_country_remove_location_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='area',
            new_name='landmarks',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='country',
            new_name='place',
        ),
    ]
